// src/utils/api.js

const BACKEND_URL = "http://127.0.0.1:8000"; // Your FastAPI address

export const analyzeEvidenceAtBackend = async (file, moduleType, officerName = "Unknown Officer", caseNum = "CAS-UNKNOWN") => {
  const formData = new FormData();
  
  // Append universal data required by ALL endpoints for the SQLite Ledger
  formData.append("file", file);
  formData.append("officer_name", officerName);
  formData.append("case_num", caseNum);

  try {
    // 1. ROUTE: FACIAL RECOGNITION (DeepFace)
    if (moduleType === "facial_recognition" || moduleType === "face") {
      const response = await fetch(`${BACKEND_URL}/analyze-face`, {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.detail || "Facial recognition backend failed.");
      }

      // Return the standardized JSON payload generated by FastAPI
      return await response.json();
    }

    // 2. ROUTE: STANDARD AI CORE (Damage, Toolmarks, Bloodstain, Ballistics)
    // The standard /analyze endpoint requires the specific Keras module_type
    formData.append("module_type", moduleType);

    const response = await fetch(`${BACKEND_URL}/analyze`, {
      method: "POST",
      body: formData,
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || "Server failed to process image.");
    }

    return await response.json();
    
  } catch (error) {
    console.error("Integration Error:", error);
    throw error;
  }
};